"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# CORE
# =========================
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev")
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"


# =========================
# HOSTS (FIX 400 en Puppeteer)
# =========================
def _split_csv(value: str) -> list[str]:
    return [x.strip() for x in (value or "").split(",") if x.strip()]

ALLOWED_HOSTS = _split_csv(os.environ.get("DJANGO_ALLOWED_HOSTS", ""))

# ✅ IMPORTANTÍSIMO: Puppeteer dentro del contenedor entra por 127.0.0.1 / localhost
for h in ["127.0.0.1", "localhost"]:
    if h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)

# Si estás en DEBUG y no pusiste nada, evita quedar vacío
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]


# =========================
# CORS / CSRF
# =========================
CORS_ALLOWED_ORIGINS = [
    "https://mvpgoaiso.com",
    "https://www.mvpgoaiso.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://mvpgoaiso.com",
    "https://www.mvpgoaiso.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# =========================
# APPS
# =========================
INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "apps.results",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "backend.urls"
WSGI_APPLICATION = "backend.wsgi.application"


# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "apps" / "base" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# DATABASE
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST", "db"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# =========================
# REST
# =========================
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


# =========================
# I18N
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# =========================
# STATIC / MEDIA
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# URLS (para PDF / Puppeteer)
# =========================
# URL pública (lo que ve el usuario)
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "https://mvpgoaiso.com")

# ✅ URL interna del backend (dentro del container)
# NO es la misma que https://www.mvpgoaiso.com/api/
# Esto es SOLO para que el propio backend se llame a sí mismo sin pasar por nginx.
BACKEND_INTERNAL_URL = os.environ.get("BACKEND_INTERNAL_URL", "http://127.0.0.1:8000")
